### ISSUE TITLE
nv 1.12: nftables broken on GitLab-hosted runners

### ISSUE THREAD

**Issue by mh21** [containers/netavark#1054]
netavark 1.12.0 switched to using nftables as the [default driver](https://github.com/containers/netavark/releases/tag/v1.12.0).

This breaks the GitLab-hosted runners which are based on Google's COS which do not have nftables available.

A minimal reproducer can be found at https://gitlab.com/cki-project/experimental/buildah-netavark-nftables-bug-gitlab/-/blob/main/.gitlab-ci.yml:

- netavark 1.12 broken job: https://gitlab.com/cki-project/experimental/buildah-netavark-nftables-bug-gitlab/-/jobs/7558910358
- netavark 1.11 working job: https://gitlab.com/cki-project/experimental/buildah-netavark-nftables-bug-gitlab/-/jobs/7558910359

Switching the buildah default FW driver via network.firewall_driver = "iptables" works, but now breaks on runners that don't have iptables available.

**Comment by Luap99** [comment]
Note we switched the default only for Fedora 41+.

>  Google's COS which do not have nftables available.

What does this mean? nft is clearly installed, does the kernel not have nftables support?

> internal:0:0-0: Error: Could not process rule: No such file or directory

This seems to be the real nft error here. Not sure why that fails though. We tested this on rawhide in in our CI VMs and it works there without issues.

**Comment by mh21** [comment]
I assume the kernel doesn't have nftables enabled; listing /proc/net/ shows only `ip_tables_*` files

**Comment by Luap99** [comment]
We are running our VMS on both GCE and AWS ec2 instances with normal fedora based cloud images/kernels so nftables just works.

If you are running special kernels without nftables support then you will need to manually configure iptables and make sure iptables is installed.

**Comment by mh21** [comment]
Hi @Luap99, these are the upstream GitLab-hosted runners.

jfyi, I don't have any beef in this discussion 🤷. I was just trying to be nice to let you know that buildah as shipped now in Fedora Rawhide will not work in any projects hosted on gitlab.com that use the runners provided by gitlab.com eg via their Open Source support.

**Comment by Luap99** [comment]
Understood, if you do not have control over these hosts then this is certainly a unfortunate situation.
Can you ask them why their kernel has no nftables kernel modules?

If you do not care about network isolation for your build jobs you can also use `--network host` to work around as well.

**Comment by mh21** [comment]
I think this is COS as shipped by Google; it might be fixed eventually by upgrading GitLab's fleet of runners to newer (?) COS versions.

**Comment by mh21** [comment]
For an example what might be needed to keep a buildah-like image with netavark 1.12 working across hosts that only have one of iptables/nftables available: https://gitlab.com/cki-project/containers/-/commit/b709813934216114f15e27656ff6b47c0099371e
