### ISSUE TITLE
Firewall rule leakage in nft backend when /udp and /tcp specified 

### ISSUE THREAD

**Issue by karuboniru** [containers/netavark#1068]
```
# installed package
$ rpm -q netavark podman 
netavark-1.12.2-1.fc40.x86_64
podman-5.2.1-1.fc40.x86_64

# using nftables
$ cat /etc/containers/containers.conf 
[containers]
userns = "auto"

[network]
firewall_driver = "nftables"

# no containers ATM
$ sudo podman ps --all                                                                               
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES

# current tables: clear
$ sudo nft list ruleset|grep 10222


$ sudo podman run -it --rm -p 10.0.1.10:10222:10222/tcp -p 10.0.1.10:10222:10222/udp alpine:latest sh
/ # exit

# check the leaked rule
$ sudo nft list ruleset|grep 10222
		udp dport 10222 jump nv_2f259bab_10_88_0_0_nm16_dnat
		tcp dport 10222 jump nv_2f259bab_10_88_0_0_nm16_dnat
		ip saddr 10.88.0.0/16 ip daddr 10.0.1.10 udp dport 10222 jump NETAVARK-HOSTPORT-SETMARK
		ip saddr 127.0.0.1 ip daddr 10.0.1.10 udp dport 10222 jump NETAVARK-HOSTPORT-SETMARK
		ip daddr 10.0.1.10 udp dport 10222 dnat ip to 10.88.0.10:10222
		ip saddr 10.88.0.0/16 ip daddr 10.0.1.10 tcp dport 10222 jump NETAVARK-HOSTPORT-SETMARK
		ip saddr 127.0.0.1 ip daddr 10.0.1.10 tcp dport 10222 jump NETAVARK-HOSTPORT-SETMARK
		ip daddr 10.0.1.10 tcp dport 10222 dnat ip to 10.88.0.10:10222
```

The key of reproducing the bug is to specify `/tcp` and `/udp` for a same port.

**Comment by karuboniru** [comment]
Simliar issue seems to be also present in iptables backend, but that only happens when one of my servers starts up, some container might fail at first time and gets restarted, lefting some firewall rules there.

Some of the rules, see the duplicate dnat from port 853 
```
sudo nft list ruleset |& grep 853
		tcp dport 853 counter packets 11 bytes 660 dnat to 10.88.0.2:853
		ip saddr 10.88.0.0/16 tcp dport 853 counter packets 0 bytes 0 jump NETAVARK-HOSTPORT-SETMARK
		ip saddr 127.0.0.1 tcp dport 853 counter packets 0 bytes 0 jump NETAVARK-HOSTPORT-SETMARK
		tcp dport 853 counter packets 0 bytes 0 dnat to 10.88.0.25:853
		tcp dport 853  counter packets 11 bytes 660 jump NETAVARK-DN-1D8721804F16F
		tcp dport 853  counter packets 0 bytes 0 jump NETAVARK-DN-1D8721804F16F
		tcp dport 853 counter packets 0 bytes 0 # Warning: XT target DNAT not found
		ip6 saddr fccc::/64 tcp dport 853 counter packets 0 bytes 0 jump NETAVARK-HOSTPORT-SETMARK
		ip6 saddr ::1 tcp dport 853 counter packets 0 bytes 0 jump NETAVARK-HOSTPORT-SETMARK
		tcp dport 853 counter packets 0 bytes 0 # Warning: XT target DNAT not found
		tcp dport 853  counter packets 0 bytes 0 jump NETAVARK-DN-1D8721804F16F
		tcp dport 853  counter packets 0 bytes 0 jump NETAVARK-DN-1D8721804F16F
```

**Comment by Luap99** [comment]
> Simliar issue seems to be also present in iptables backend, but that only happens when one of my servers starts up, some container might fail at first time and gets restarted, lefting some firewall rules there.

This doesn't sounds related to this issue. Even if the first start would fail the second one would create the exact same iptables rules AFAIK so there should be no leaks on stop. Please file anew issue with a proper reproducer for that.

**Comment by Luap99** [comment]
@mheon I tried to look at this and matching these rules on teardown seem rather complicated. All have their own customer rule_match that is very different from how we actually create the rule. Shouldn't we share the code for setup and teardown to create the same rule once and then just remove it? Does the nft json commands care if we delete a rule that doesn't exists? If it doesn't work I still think the match code has to match the full rules not just parts of it because in my eyes this is to error prone right now. I would much rather have code like in iptables where we build the same rules for both.

**Comment by mheon** [comment]
@Luap99 We need to retrieve the rules from the running config in order to delete them; we cannot recreate, we need the actual rule from running config to remove. So running the same code twice is a no-go.

**Comment by Luap99** [comment]
@mheon Ack reading a bit more I guess we have to list the rule to get the handle id as this seems to be used when removing. But I still think we could fix the "match rule" code to match against the same rule we create on setup instead of having to maintain a separate matcher for a rule we already know how to build.

**Comment by mheon** [comment]
I deliberately did not do that because it seemed very complicated to build a proper matcher that could do arbitrary rule against arbitary rule, but it would certainly simplify the code if it were done.

**Comment by karuboniru** [comment]
> Even if the first start would fail the second one would create the exact same iptables rules AFAIK so there should be no leaks on stop

No, they don't seem to be exact. Since multiple containers are starting simultaneously, the second instance would have a different ip address.
