### ISSUE TITLE
vlan for bridge

### ISSUE THREAD

**Issue by baude** [containers/netavark#108]
i cannot remember this one

**Comment by flouthoc** [comment]
Thanks picking this up.

**Comment by flouthoc** [comment]
@Luap99 @baude I have a question do we also need to create `vlan` interface or just want to tag the `bridge` with something equivalent to `bridge vlan add dev DEV vid VID [ pvid ] [ untagged ] [ self ] [ master ]`

**Comment by Luap99** [comment]
@flouthoc I have not looked at the cni code but we should match what they are doing IMO

**Comment by flouthoc** [comment]
They are also creating `vlan` interface but our config does not have a option to specify should i add it.

**Comment by Luap99** [comment]
Why do you need a new field? The vlan number + interface name should name should be enough. https://www.cni.dev/plugins/current/main/bridge/

**Comment by flouthoc** [comment]
Upstream is missing support for setting `bridge flags` and `bridge vlan info`. I am plumbing upstream to support this.

**Comment by flouthoc** [comment]
There are few PR's waiting here to be merge. I don't know what else is missing but I'll figure it out https://github.com/little-dude/netlink/pulls
