### ISSUE TITLE
netavark for rootless containers

### ISSUE THREAD

**Issue by PHHENS** [containers/netavark#1089]
Dear developer,

Would like to use netavark dhcp-proxy for rootless containers.
I found "netavark -r true" options, so I've tested "netavark -r true dhcp-proxy".
But did not manage to make it work with rootless containers ...
How is it supposed to work ?

Thanks for your help.

**Comment by Luap99** [comment]
That is impossible, rootless netavark runs in a separate namesapce (rootless-netns) so thee is no way to use macvlan on a host device to get dhcp packets anyway
ref https://github.com/containers/podman/discussions/22943#discussioncomment-9795883
