### ISSUE TITLE
Debian package is missing netavark-dhcp-proxy.socket and .service

### ISSUE THREAD

**Issue by hachi** [containers/netavark#1128]
It's just not there... I discovered this by trying to do:

# systemctl enable --now netavark-dhcp-proxy.socket
Failed to enable unit: Unit netavark-dhcp-proxy.socket does not exist

Here's the file listing of the package https://packages.debian.org/sid/amd64/netavark/filelist

**Comment by Luap99** [comment]
You need to report that to the debian maintainer as debian bug, upstream has no control over distribution packages
