### ISSUE TITLE
Investigate ways to vendor build dependencies

### ISSUE THREAD

**Issue by lsm5** [containers/netavark#115]
Vendoring build dependencies will make downstream packaging a lot easier. cargo-vendor seems like the way to go, but it hasn't been updated in 3 years now, and crates.io doesn't mention anything about its deprecation.

Are there any other solutions?

**Comment by flouthoc** [comment]
@lsm5 So i checked I think you are referring to the old repository https://github.com/alexcrichton/cargo-vendor however `cargo vendor` is merged with `cargo` and being maintained actively https://github.com/rust-lang/cargo. 

> but it hasn't been updated in 3 years now, and crates.io doesn't mention anything about its deprecation
Same this is not the active repository for `cargo-vendor` https://crates.io/crates/cargo-vendor its already part of a latest `cargo` so its being shipped with native stack we don't need to download it manually from `crates.io`.

Its a native `cargo` feature now not a external dependency anymore.

**Comment by lsm5** [comment]
@flouthoc great, can we start vendoring upstream soon as it's feasible? As a packager, I think it's best to have this in place at the earliest. RHEL will 100% depend on this and I'm gonna push for this in Fedora as well. Because it's just plain torture to package this in Fedora with the existing `rust-foobar-devel` dependencies, assuming it's even possible at all.

**Comment by flouthoc** [comment]
@lsm5 Created a PR please take a look

**Comment by lsm5** [comment]
Vendoring is available upstream now. Thanks all.
