### ISSUE TITLE
Error: unsupported macvlan network option mtu

### ISSUE THREAD

**Issue by baude** [containers/netavark#151]
When running the e2e tests with netavark, we get a failure with `Error: unsupported macvlan network option mtu`.  See https://github.com/containers/podman/blob/main/test/e2e/network_test.go#L574

**Comment by Luap99** [comment]
https://github.com/containers/common/blob/97814789b1bb4fac1a2ddaebcaf9873c457f4625/libnetwork/netavark/config.go#L127-L137

**Comment by Luap99** [comment]
I will open a PR to fix it in c/common if you add support to netavark.

**Comment by flouthoc** [comment]
@Luap99 Sure I'll add it to netavark. We have to stop blocking it from `c/common/` thanks.

**Comment by Luap99** [comment]
https://github.com/containers/common/pull/881
