### ISSUE TITLE
macvlan needs to be able to do dhcp

### ISSUE THREAD

**Issue by baude** [containers/netavark#152]
The e2e tests assume dhcp is available with macvlan.

Error: macvlan driver needs at least one subnet specified, DHCP is not supported with netavark

Example -> https://github.com/containers/podman/blob/main/test/e2e/network_test.go#L529

**Comment by Luap99** [comment]
DHCP support is complicated because it requires a daemon. I would say we should skip this for now.

**Comment by baude** [comment]
lets keep our eye on this ... else it is a regression from cni

**Comment by Luap99** [comment]
Well it is not easy to implement and we have a lot of other things to do. The regression argument doesn't count IMO since we still support CNI for those who need it.

**Comment by flouthoc** [comment]
I accidentally attached this issue to wrong PR that's why it got closed. Thanks for re-opening.

**Comment by Jackbaude** [comment]
Can I take this one?

**Comment by baude** [comment]
@Jackbaude we will send people running into the hills!

**Comment by briankoco** [comment]
Expressing my support for this feature. Macvlan is ideal for containerized deployments that you want to have access to a DHCP server on your physical network

**Comment by Jackbaude** [comment]
I have started a [crate](https://github.com/Jackbaude/netavark-dhcp-proxy) for the proxy daemon.
