### ISSUE TITLE
Look into blocking/permitting network to network communication

### ISSUE THREAD

**Issue by baude** [containers/netavark#154]
See https://github.com/containers/podman/issues/5805

**Comment by Luap99** [comment]
Is this the correct linked issue? Your title sounds like https://github.com/containers/podman/issues/5805

**Comment by baude** [comment]
yup, i had a hiccup during that one

**Comment by cdoern** [comment]
@mheon would this just require adding a rule to not allow external connections: 

https://github.com/containers/netavark/blob/6eab33518566c9f024c81308046ea8d9714c4044/src/firewall/varktables/types.rs#L207-L217

Just trying to get a feel for if I am looking in the right spot

**Comment by mheon** [comment]
No, that's a standard rule to allow existing connections always - we shouldn't mess with that.

I'd probably do this as an outbound traffic rule - anything from a Podman network to another podman network should be dropped. For N networks, you'll probably need N sets of N-1 rules (each network has to have a set of rules banning traffic beginning in its subnet from reaching every other network's subnets).

The same could definitely be done on network ingress - really just a matter of preference as to where the rules go. I'll look a bit more into where they could be placed later.

**Comment by Luap99** [comment]
This is what is done for cni https://github.com/AkihiroSuda/cni-isolation#how-it-works
