### ISSUE TITLE
use optimistic_dad instead of disabling DAD

### ISSUE THREAD

**Issue by Luap99** [containers/netavark#260]
Thanks to sbrivio_ on IRC for the pointer

**Comment by flouthoc** [comment]
@Luap99 Could you please add more context to this issue. Like why is there is need to enable `DAD`.

Few cons an

* This might be still slow if something is wrong in our setup.
* [Not a big issue] but older kernels do not support `optimistic_dad` 
* Do we need to turn on router advertisement as well ?

**Comment by Luap99** [comment]
RHEL8 will support this, it was added some time in 3.X

**Comment by rhatdan** [comment]
Great.
