### ISSUE TITLE
Netavark bridge cannot duplicate CNI layer 2 bridge capability

### ISSUE THREAD

**Issue by xinato** [containers/netavark#311]
With CNI, I was able to create a layer 2 network bridge device using networkmanager with my hardware ethernet card as a bound device. The address of the bridge is my hosts IP on the network. Containers using CNI bridging are able to bind to the bridge and obtain static addresses on the external network. It's been a while, but I think the containers could also get addresses from the dhcp server on the net.

With netavark, it looks like I have to have layer 3 bridging (routing) where the containers are in a subnet. The subnet then needs a gateway interface to the external net. It looks like MAC vlans also need to be on a subnet, with a gateway. 

Is there a reason that netavark works differently and does not support the layer 2 bridging? Or have I not found the magic yet that makes layer 2 bridging work?

**Comment by Luap99** [comment]
Can you provide more context. How does your cni config looks like?

But this sounds like a macvlan setup, the subnet/gateway is required because we do not have dhcp support yet. You could also use ipam none driver to not assign any ip addresses and assign them manually then.

Bridge for use means an separate interface that is managed by us and not shared with the host. This is also how it worked with the default cni configs.

We are open to contributions if people want to add support for more.

**Comment by xinato** [comment]
Thank you very much for looking at my issue! My setup is not a MAC VLAN setup. I am using type: bridge and referencing my br0 that is setup by networkmanager.

Using CNI, my ifconfig for the eth0 and  br0 as setup by nmcli are:

 ifconfig 
br0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.16.66.10  netmask 255.255.255.0  broadcast 172.16.66.255
        inet6 2601:401:180:eb30:6f81:6547:54ae:f2c1  prefixlen 64  scopeid 0x0<global>
        inet6 2601:401:180:eb30::2  prefixlen 128  scopeid 0x0<global>
        inet6 fe80::7f10:e78a:5ede:953  prefixlen 64  scopeid 0x20<link>
        inet6 2601:401:180:eb30:c0d5:6f76:4e52:6f1e  prefixlen 64  scopeid 0x0<global>
        inet6 2601:401:180:eb30:7ddc:c60c:11a2:c711  prefixlen 64  scopeid 0x0<global>
        inet6 2601:401:180:eb30:5257:38ff:feea:34f6  prefixlen 64  scopeid 0x0<global>
        ether 52:57:38:ea:34:f6  txqueuelen 1000  (Ethernet)
        RX packets 702107  bytes 390154073 (372.0 MiB)
        RX errors 0  dropped 7817  overruns 0  frame 0
        TX packets 487092  bytes 312075737 (297.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether 6c:62:6d:80:ac:2b  txqueuelen 1000  (Ethernet)
        RX packets 436425  bytes 350034498 (333.8 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 288762  bytes 63205209 (60.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

------------The network configuration for a container is:

{
  "cniVersion": "0.4.0",
  "name": "172.16.66.13",
  "plugins": [
    {
      "type": "bridge",
      "bridge": "br0",
      "isGateway": false,
      "ipMasq": false,
      "hairpinMode": false,
        "ipam": {
                "type": "static",
                "addresses": [
                        {
                                "address": "172.16.66.13/24",
                                "gateway": "172.16.66.1"
                        }
                ],
                "routes": [
                        { "dst": "0.0.0.0/0",  "gw": "172.16.66.1" }
                ],
                "dns": {
                        "nameservers" : ["75.75.75.75",
                                         "75,75,76,76",
                                         "2001:558:feed::1",
                                         "2001:558:feed::2"
                                        ],
                        "domain": "arbershire.com",
                        "search": [ "arbershire.com" ]
                }
            }
        }
  ]
}


-----------------The container is setup as a new interface on the the existing br0.

-----------------This is seen with ip (using the NS key for the container)
ipwkey serviio add sho
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0@if13: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether a2:8c:40:71:ad:19 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.16.66.13/24 brd 172.16.66.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2601:401:180:eb30:a08c:40ff:fe71:ad19/64 scope global dynamic mngtmpaddr 
       valid_lft 345593sec preferred_lft 345593sec
    inet6 fe80::a08c:40ff:fe71:ad19/64 scope link 
       valid_lft forever preferred_lft forever

---------------I am encouraged by what you said about using ipam none driver. I will experiment with that. Would I still need to setup a subnetwork and router interface to make this a layer 3 bridge?

I don't pretend to be fluent enough to contribute. I will take a look at the code and see if I can understand it.

**Comment by Luap99** [comment]
The bridge driver expects that it has full control over the interface, it will remove the interface once all container on the network are stopped. So you definitely should not use it with your own interfaces.

I think macvlan sounds more like what you want. With macvlan you just set the host interface where you want the container interface to connect to. There is no need for the extra veth interface on the host side.

**Comment by xinato** [comment]
Thank you for suggesting the macvlan approach. In this application it does seem to work. I notice a difference between macvlan and the approach I was using. When I connected using a CNI bridge to the OS level bridge, I was able to communicate between the host and the container through the network. With the macvlan setup under Netavark, this connection is "unreachable." Descriptions of macvlan I have read say this host/container connection should work. Perhaps a "hairpin" option in the driver would be possible. It seems logical that two devices with mac addresses and IP addresses on the same network should be able to communicate.

Thank you again.

**Comment by xinato** [comment]
Besides the previous issue, I ran into an issue where the container with a macvlan does not take the mac address from the run command. Also, the network includes working IPV6 even though I did not specify it (a feature, not a bug).

To replicate:

:podman run --rm -it --network 172.16.66.0-macvlan --mac-address=a2:8c:40:71:ad:19 --ip=172.16.66.66 --name test localhost:5000/myfedora-minimal bash

Check the container with the network key

: ipwkey test add sho
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
12: eth0@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 32:e7:64:d9:16:31 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.16.66.66/24 brd 172.16.66.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2601:401:180:eb30:30e7:64ff:fed9:1631/64 scope global dynamic mngtmpaddr 
       valid_lft 345593sec preferred_lft 345593sec
    inet6 fe80::30e7:64ff:fed9:1631/64 scope link 
       valid_lft forever preferred_lft forever

My network is:
: podman network inspect 172.16.66.0-macvlan
[
     {
          "name": "172.16.66.0-macvlan",
          "id": "c5a708abac222a0ad36189a1c3a1a26be8c117799150de5b5eac2058c10a5ea1",
          "driver": "macvlan",
          "network_interface": "eth0",
          "created": "2022-07-09T07:22:56.657713327-04:00",
          "subnets": [
               {
                    "subnet": "172.16.66.0/24",
                    "gateway": "172.16.66.1"
               }
          ],
          "ipv6_enabled": false,
          "internal": false,
          "dns_enabled": true,
          "ipam_options": {
               "driver": "host-local"
          }
     }
]

**Comment by tobwen** [comment]
I'm also interested in this behavior.

**Comment by cveilleux** [comment]
+1 on this simple behavior that CNI supports. I am worried that podman will drop CNI support without covering this feature in netavark.

I am running podman on a specialized network distro (think firewall-type-machine).

The firewall daemon creates a bridge (br0) and connects wifi access point interfaces and physical ethernet interfaces. Vlan filtering is used to control layer2 traffic.

It is then super easy to expose services to the network clients using the following CNI network:

```json
{
    "cniVersion": "0.4.0",
    "name": "vlan10",
    "plugins": [
        {
            "type": "bridge",
            "bridge": "br0",
            "vlan": 10,
            "ipam": {
                "type": "dhcp"
            },
            "dns": {
                "nameservers": [
                    "192.168.10.1"
                ]
            }
        },
        {
            "type": "portmap",
            "capabilities": {
                "portMappings": true
            }
        },
        {
            "type": "firewall"
        },
        {
            "type": "tuning"
        }
    ]
}
```

Containers are then bridged straight to the pre-existing br0 bridge and they get IP+DNS configured just like any other physical client devices on the network. This is really a wonderful and clean integration for us. We can tread containers just as any other network clients and all rules and features just work. Think port forwards, VPNs, ACLs, etc etc.. 

I understand the current code-base assumes full control on the bridge interface can destroy it, etc.. but there must be a way around it?

**Comment by Luap99** [comment]
Reading this again I think `podman network create --ipam-driver none` should already work and not assign a subnet.

**Comment by xinato** [comment]
I solved this issue another way. I used pasta to create my network without a bridge. It clones my host Ethernet adapter inside my rootless container. This is simple an works well.

**Comment by tobwen** [comment]
> I solved this issue another way. I used pasta to create my network without a bridge. It clones my host Ethernet adapter inside my rootless container. This is simple an works well.

Could you please give an example to help the community? Others might run in similar problems.

**Comment by space88man** [comment]
This seems to work out-of-the-box now.

Prerequisites: host has bridged network created by NetworkManager

```
# Example NetworkManager bridge
NAME = main
DEVICE = nm-main
HOST SLAVE = enp6s0
```

Netavark seemingly will accept the existing bridge device `nm-main` and not wrest control:

```
# rootful networking
sudo podman network create --ipam-driver none --interface-name nm-main --disable-dns
# creates "podman3" network

sudo podman inspect podman3
[
     {
          "name": "podman3",
          "id": "b979df8873ca4beb9d6d5e4bd5fd2661982e7b450ee205116df9de1c8ab0852f",
          "driver": "bridge",
          "network_interface": "nm-main",
          "created": "2024-06-26T13:48:43.263516655+08:00",
          "ipv6_enabled": false,
          "internal": false,
          "dns_enabled": false,
          "ipam_options": {
               "driver": "none"
          },
          "containers": {}
     }
]
```

Verification
```
sudo podman run --name test_1 --network podman3 -it almalinux:9 /bin/bash
[root@9fd1cc41b0a9 /]#

ip link show master nm-main
2: enp6s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq master nm-main state UP mode DEFAULT group default qlen 1000
    link/ether 4c:ed:fb:79:a1:ae brd ff:ff:ff:ff:ff:ff
6: veth0@if2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master nm-main state UP mode DEFAULT group default qlen 1000
    link/ether f2:e1:4b:b3:9f:d3 brd ff:ff:ff:ff:ff:ff link-netns netns-7f8aa752-8389-c75d-4f33-9c7ba3b23d91

## now inside the container add IP address/default gateway
## test ping etc
```
