### ISSUE TITLE
Please publish to crates.io

### ISSUE THREAD

**Issue by siretart** [containers/netavark#318]
Any chance to have netavark published on crates.io?

**Comment by flouthoc** [comment]
Hi @siretart , Thanks for creating the issue.

If i remember correctly we had a discussion on this one issue is that `netavark` as of now is always used as a dependency of `podman` where `podman` installs netavark on a specific path where other podman executable dependencies are stored and netavark in itself is not very useful without podman so shipping it as individual CLI might be not useful for users.

But I could be missing few points and it might be good idea to reevaluate this.

@lsm5 @Luap99 @mheon @baude WDYT

**Comment by baude** [comment]
@flouthoc lets support Debian here ... what do folks want?  Should we cut a new release and then also package on crates.io so everything lines up?

**Comment by Luap99** [comment]
@baude lets wait with the next release, we have to get https://github.com/little-dude/netlink/pull/274 in. Netavark is currently broken on kernel 5.19.

**Comment by baude** [comment]
@Luap99 that begs the question, should we publish it for the last release so @siretart can still package?

**Comment by Luap99** [comment]
sure, just push the latest version. I assume we want to do the same for aardvark-dns then?

**Comment by flouthoc** [comment]
Yeah we can publish both netavark and aardvark-dns. I'll check this.

**Comment by flouthoc** [comment]
Published two versions (dirty) for `1.0.3` and `1.0.4-dev` to try out https://crates.io/crates/netavark and https://crates.io/crates/netavark release from `1.0.4` should be clean. @siretart Could you please try above.

**Comment by flouthoc** [comment]
@siretart Feel free to close the issue if this works for you :)

**Comment by siretart** [comment]
I will follow-up. Right now, for some reason debcargo claims to not find them, but a `cargo search` does. Go figure.

I've managed to package `netavark` with non-vendored sources at https://salsa.debian.org/debian/netavark. I'm still waiting for some dependencies to get through initial ftp archive admin review, but I.m getting really close (finally).

**Comment by flouthoc** [comment]
@siretart Thanks for the update :)

**Comment by Luap99** [comment]
@flouthoc Can you upload the newer versions?
Also I guess it would be great if you can give @baude and @mheon access so we can make this part of the release process.
