### ISSUE TITLE
isolate nor working correctly

### ISSUE THREAD

**Issue by Luap99** [containers/netavark#331]
While testing cni isolate option against the netavark one I found some issues.

- IPv6 rules are not created, therefore ipv6 traffic is not isolated at all.
- Isolation blocks all external communication which is wrong, this is what internal is used for. If we want to follow what docker/cni does we should only block communication between two isolated networks.

This should be fixed before we make a new release.

**Comment by mheon** [comment]
The second one sounds like something we should be testing in CI

**Comment by Luap99** [comment]
We are testing but the main problem is that nobody from us seems to understand what isolate should do exactly.
I already have local changes to match CNI/docker rules.
