### ISSUE TITLE
[Feature Request] An option to disable a firewall setup.

### ISSUE THREAD

**Issue by vimusov** [containers/netavark#400]
Hi!
In the CNI there is an option `ipMasq` [^1] which allows you to disable a firewall setup. As I see there is no equal option in the Netavark. So I'd like to propose to implement it. I think it'd be useful for many users.
Thanks for your attention!
[^1]: https://www.cni.dev/plugins/current/main/bridge/

**Comment by Luap99** [comment]
Duplicate of #339

**Comment by vimusov** [comment]
Oh, sorry for that. I didn't notice this issue.
