### ISSUE TITLE
Internal networks should not have a gateway

### ISSUE THREAD

**Issue by astenmco** [containers/netavark#415]
When creating an internal network, netavark gives it a gateway.
Worse : when connecting a container to this network, the gateway is set as "default gateway".

The default behavior when creating an internal network should be not to assign it a gateway.
At least, we should have the possibility to explicitly not set a gateway.

```console
# podman network create --driver bridge --subnet 10.127.0.0/16 --internal internal
# podman network inspect internal
[
     {
          "name": "internal",
          "id": "c259e2b6cec93c896d8abebd5d98d85790e3e9e306970786268098eeb9eacbce",
          "driver": "bridge",
          "network_interface": "podman2",
          "created": "2022-09-22T15:48:55.780025615+02:00",
          "subnets": [
               {
                    "subnet": "10.127.0.0/16",
                    "gateway": "10.127.0.1"
               }
          ],
          "ipv6_enabled": false,
          "internal": true,
          "dns_enabled": true,
          "ipam_options": {
               "driver": "host-local"
          }
     }
]
# podman run --net internal alpine ip route
default via 10.127.0.1 dev eth0
10.127.0.0/16 dev eth0 scope link  src 10.127.0.2
```

I have podman version 4.1.1 with netavark 2:1.0.1-35

**Comment by Luap99** [comment]
I take a look sorry for the delay.

**Comment by Luap99** [comment]
Looks like our regression test is broken: https://github.com/containers/netavark/blob/0b04857d9b3eea88029a1f03f418a2384913f679/test/100-bridge-iptables.bats#L25-L26
I can confirm that the default route is created but the test still passes.
