### ISSUE TITLE
firewalld - Error retrieving dbus connection

### ISSUE THREAD

**Issue by SecT0uch** [containers/netavark#498]
I recently migrated from iptables to firewalld + nftables.

Using: `NETAVARK_FW="firewalld" podman-compose up -d` I get `netavark: Error retrieving dbus connection for requested firewall backend: DBus error: I/O error: No such file or directory (os error 2)`.

Is netavark currently supposed to work with firewalld ?

I see [this comment in the code](https://github.com/containers/netavark/blob/65afcb3303cc9e33c84fc2b5691545de0015ff9a/src/firewall/mod.rs#L64) while firewalld 1.2.1 is out.

Edit: 
* `Linux core 5.15.79-0-lts #1-Alpine SMP Thu, 17 Nov 2022 08:14:03 +0000 x86_64 Linux`
* Podman 4.3.1
* firewalld 1.2.1

**Comment by Luap99** [comment]
Well rootless cannot use firewalld, rootless podman uses a completely different namespace where firewalld will not exists.

**Comment by mheon** [comment]
Error isn't specific to firewalld, it's more an unexpected error trying to grab a dbus session to determine if firewalld even exists. I would expect that to work with rootless.

**Comment by Luap99** [comment]
No, the dbus socket will likely not exists in the rootless namespace, we need to remount a bunch of stuff to /run to make iptables and CNI work, /run/dbus is not one of them because it is not required so the socket does not exists.
And this is fine since the rootless users has no permission to talk to firewalld anyway.

**Comment by mheon** [comment]
I believe we're ignoring most errors for the purpose of this, on the assumption that dbus may not be available. Which makes this one even more curious...

Any chance the NETAVARK_FW environment variable is defined?

**Comment by Luap99** [comment]
> Any chance the NETAVARK_FW environment variable is defined?

yes see original report, that is the point of the issue

**Comment by mheon** [comment]
Oh. Yeah, this is 100% expected then; force a firewall backend that requires dbus in a rootless environment without dbus, and errors will result.

I think we can close given this.

**Comment by SecT0uch** [comment]
So to resume:
* rootless podman + firewald: Impossible
* rootless podman + iptables: Possible
* rootless podman + nftables: Possible

Is that correct ?

**Comment by Luap99** [comment]
yes
