### ISSUE TITLE
Howto handle two static IPv6 addresses

### ISSUE THREAD

**Issue by fansari** [containers/netavark#535]
I have a pod with an ULA and a public IP.

For both kind of IP addresses I would like to configure them static.

But I noticed when I use the "--ip6" parameter twice only the last one is recognized. I see this after I create a container in this pod.

In this example I would get the public IP the way I configured it and the ULA gets random.

When I exchange the sequence it is the other way round.

How can I have both IPv6 addresses static?

```
  "CreateCommand": [
          "podman",
          "pod",
          "create",
          "--network=podman1",
          "--name=dns",
          "--dns",
          "::1",
          "--dns-search=localdomain",
          "--ip=10.90.0.2",
          "--ip6=fdc2:xxxx:xxxx:f3c0:ff::2",
          "--ip6=2a02:xxxx:xxxx:xxxx:ff::2"
     ],
```

**Comment by Luap99** [comment]
This is not a netavark issue, you have to use the --network syntax, `--network name:ip=ip1,ip=ip2,...`
