### ISSUE TITLE
Error: macvlan driver needs at least one subnet specified, DHCP is not yet supported with netavark

### ISSUE THREAD

**Issue by nkartem** [containers/netavark#546]
`podman network create -d macvlan -o parent=eth0 net_sip`
Error: macvlan driver needs at least one subnet specified, DHCP is not yet supported with netavark

**Comment by baude** [comment]
It means it is not supported yet through podman.  I have just merged support in netavark so technically it is there.  podman support will be coming in the next few weeks.

do you have a question here?
