### ISSUE TITLE
Flake: not ok 14 iptables: Ncat: Connection refused.

### ISSUE THREAD

**Issue by cevich** [containers/netavark#574]
On multiple occasions this test fails with `Ncat: Connection refused.`.  I noticed in the resource-graphs, there is a giant spike in memory usage up to 5+gig suggesting perhaps the OOM-killer is taking action.  Example failures:

* https://cirrus-ci.com/task/4555929878790144
* https://cirrus-ci.com/task/5530635595415552
* https://cirrus-ci.com/task/5927662238040064

**Comment by Luap99** [comment]
Already tracked in https://github.com/containers/netavark/issues/433

**Comment by cevich** [comment]
Thanks Paul.
