### ISSUE TITLE
Setting only one aardvark-dns path may cause inconvenience

### ISSUE THREAD

**Issue by unknowndevQwQ** [containers/netavark#607]
https://github.com/containers/netavark/blob/6bc7e385f6c7eaa8ff3117d4ad19e98b4d0ddd19/src/main.rs#L49

Using a unique default value directly without specifying the --aardvark-binary argument has several possible disadvantages.

1. not all distributions distinguish between lib and libexec, and distributions that do not have this behavior may require additional patching to make netavark work.
2. aardvark may be installed in /usr/local/lib{,exec} when using a third-party package manager or when installing manually (I'm not quite sure if netavark allows users to do this).

**Comment by Luap99** [comment]
Podman chooses the location and always sets the correct path based on helper_binaries_dir from contianers.conf.
There is no need to change the default in netavark

**Comment by baude** [comment]
closing
