### ISSUE TITLE
compine netavark and dhcp-proxy into one binary

### ISSUE THREAD

**Issue by Luap99** [containers/netavark#608]
Now that we merged the repos I suggest that we merge both binaries into one, i. e. instead of calling `netavark-dhcp-proxy` we would call `netavark dhcp-proxy` and implement it as subcommand.

The main benefit would be reduced binary size. Because rust libs are statically linked and both binaries mostly use the same code they are duplicated in each binary. If we combine them it would reduce the overall size.

@baude @mheon @flouthoc WDYT?

**Comment by mheon** [comment]
I have no objections, though I would like to know how much of an impact on binary size it has for pure-NV installations.

**Comment by Luap99** [comment]
I can test but I do not think it has much if any. netavark already contains the tokio async and protobuf RPC stuff because it has to talk to server vie RPC.

**Comment by baude** [comment]
if you combine the two binaries, you no longer need tokio or async ... this is completely counter to the design that was created and agreed to.  the upside is it all but eliminates the heavy complexity of the proxy code.

**Comment by Luap99** [comment]
> if you combine the two binaries, you no longer need tokio or async ... this is completely counter to the design that was created and agreed to. the upside is it all but eliminates the heavy complexity of the proxy code.

I think you misunderstood me. All I am asking for is `netavark dhcp-proxy`. Basically the cli frontend will call main() of the current code when the subcommand is called. They are still completely separated in code just that they are part of one binary to reduce bloat caused by the static linking.

**Comment by baude** [comment]
darn it ... that would have solved a number of things! :)

**Comment by baude** [comment]
no objection here

**Comment by Luap99** [comment]
I did a quick test, combined we get one binary with 18 MB.
Right now we have two: netavark is 15 MB and netavark-dhcp-proxy is 13 MB.

So in total we safe about 10 MB by doing this.
