### ISSUE TITLE
Spcifying MAC address for multiple networks.

### ISSUE THREAD

**Issue by brainiac19** [containers/netavark#728]
I need to specify MAC address for containers that acquires DHCP lease from a MACVLAN network, so I can manage them all in static DHCP lease, but that doesn't seem supported yet. I tried the `mac` and `mac_address` keys, but they didn't work under named network config, I still see random MAC asking for DHCP lease from the DHCP server. Specifying `mac_address` is only allowed when a container joins only a single network, and the `mac_address` is a property of that entire container, not just a network. Just bringing it up since I do think this feature should be supported, eventually.

**Comment by Luap99** [comment]
This already works, if you want to assign static ips or macs  for multiple network use the --network <name>:mac=... syntax
https://docs.podman.io/en/latest/markdown/podman-create.1.html#network-mode-net

**Comment by brainiac19** [comment]
Looks like I'm just naive to assume it's supported by compose. I'll submit an issue there.
