### ISSUE TITLE
dns not availabale in container when using bridge network and default INPUT policy on host is DROP

### ISSUE THREAD

**Issue by Peter-Sh** [containers/netavark#742]
### Description

When running container in non default podman network with dns enabled and default INPUT host firewall policy is DROP (or last INPUT rule is reject), name resolution does not work in container. This is because aardvark-dns listens on bridge interface ip address and packets from containers go through hosts INPUT chain.
This happens in IPv4 and IPv6 networks.

### Steps to reproduce

Used fresh Fedora 38 and podman from repository.

Create network
```
podman network create podman1
```

Set default INPUT policy to DROP
```
iptables -P INPUT DROP
```

Allow related connections
```
iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
```

Start container in podman1 network
```
podman run --rm -it --network podman1 docker.io/alpine:3.18.2
```

Check name resolving
```
getent ahosts podman.io
```

**Result:** name **is not** resolved, user is surprised.

**Expected result:** name is resolved.

### Workaround

Add firewall rule to allow dns traffic
```
iptables -A INPUT -p udp -s {NETWORK_SUBNET} --dport 53 -j ACCEPT
```

### Possible fix

Always add ACCEPT rules in firewall for dns traffic from containers to gateway when using bridge network with internal dns.

### Versions
podman 4.5.1
netavark 1.6.0
OS: Fedora 38

**Comment by Luap99** [comment]
Thanks for the report, do you want to open a PR to add the necessary rule?

**Comment by Peter-Sh** [comment]
> Thanks for the report, do you want to open a PR to add the necessary rule?

Good idea, but I do not code in Rust (yet?) :)
