### ISSUE TITLE
Consider replacing mandown

### ISSUE THREAD

**Issue by benjamb** [containers/netavark#768]
The project appears to be unmaintained and doesn't ship a Cargo.lock, thus does not provide deterministic builds. An MR was opened to address this 3 months ago, but hasn't seen any activity from upstream, neither has the `master` branch of the repository seen any activity in over a year.

Fedora currently make use of `go-md2man` in their [spec file](https://src.fedoraproject.org/rpms/netavark/blob/f38/f/netavark.spec#_47), though I can only speculate as to their reasoning. Debian's [fork](https://salsa.debian.org/debian/netavark/-/tree/debian/sid/debian) for sid doesn't even seem to install man pages at this point, but I don't see them packaging `mandown` in it's current state.

**Comment by Luap99** [comment]
I have no problem switching to `go-md2man`, it is was we use for other projects as well so we know it works good enough for us.

Are you interested in opening a PR to switch out Makefile?
