### ISSUE TITLE
`netavark 1.8.0` build failure with release vendor crates

### ISSUE THREAD

**Issue by jpalus** [containers/netavark#819]
Build of `netavark 1.8.0` with vendor crates taken from a `1.8.0` release fails for me ie (`rust 1.72.1`):
```console
error[E0432]: unresolved imports `event_listener::Event`, `event_listener::EventListener`
 --> /home/users/builder/rpm/BUILD/netavark-1.8.0/vendor/async-lock/src/barrier.rs:1:22
  |
1 | use event_listener::{Event, EventListener};
  |                      ^^^^^  ^^^^^^^^^^^^^ no `EventListener` in the root
  |                      |
  |                      no `Event` in the root

error[E0432]: unresolved imports `event_listener::Event`, `event_listener::EventListener`
  --> /home/users/builder/rpm/BUILD/netavark-1.8.0/vendor/async-lock/src/mutex.rs:20:22
   |
20 | use event_listener::{Event, EventListener};
   |                      ^^^^^  ^^^^^^^^^^^^^ no `EventListener` in the root
   |                      |
   |                      no `Event` in the root

error[E0432]: unresolved imports `event_listener::Event`, `event_listener::EventListener`
  --> /home/users/builder/rpm/BUILD/netavark-1.8.0/vendor/async-lock/src/once_cell.rs:10:22
   |
10 | use event_listener::{Event, EventListener};
   |                      ^^^^^  ^^^^^^^^^^^^^ no `EventListener` in the root
   |                      |
   |                      no `Event` in the root

error[E0432]: unresolved imports `event_listener::Event`, `event_listener::EventListener`
  --> /home/users/builder/rpm/BUILD/netavark-1.8.0/vendor/async-lock/src/rwlock/raw.rs:16:22
   |
16 | use event_listener::{Event, EventListener};
   |                      ^^^^^  ^^^^^^^^^^^^^ no `EventListener` in the root
   |                      |
   |                      no `Event` in the root

error[E0432]: unresolved imports `event_listener::Event`, `event_listener::EventListener`
 --> /home/users/builder/rpm/BUILD/netavark-1.8.0/vendor/async-lock/src/semaphore.rs:8:22
  |
8 | use event_listener::{Event, EventListener};
  |                      ^^^^^  ^^^^^^^^^^^^^ no `EventListener` in the root
  |                      |
  |                      no `Event` in the root
```
Build succeeds if crates are vendored with `cargo vendor` (comparing contents of `cargo vendor` output and `netavark-v1.8.0-vendor.tar.gz` shows many differences).

**Comment by rahilarious** [comment]
yep. Same here. I'm surprised even after rc1 and this much of CI, such stuff happen at release

**Comment by Luap99** [comment]
@baude PTAL

**Comment by Luap99** [comment]
I can reproduce even recreating the vendored deps locally with make vendor-tarball. Seems like cargo-vendor-filterer is replacing required deps for some reason.

**Comment by flouthoc** [comment]
@Luap99 I think vendor can be still prepared by using older diff from here: https://github.com/containers/netavark/commit/f07cc0435e8c96e8b64204ff4c080b50b9d8f15b and then `cargo-vendor-filterer` can be debugged later ?

**Comment by Luap99** [comment]
> @Luap99 I think vendor can be still prepared by using older diff from here: [f07cc04](https://github.com/containers/netavark/commit/f07cc0435e8c96e8b64204ff4c080b50b9d8f15b) and then `cargo-vendor-filterer` can be debugged later ?

Yes I updated the tarball now on the release so it should work now, I still leave this open until we know why cargo vendor-filterer does not work correctly.

**Comment by flouthoc** [comment]
@Luap99 Should it be manually published for aardvark-dns as well ? I suspect same issue will be there.

**Comment by Luap99** [comment]
> @Luap99 Should it be manually published for aardvark-dns as well ? I suspect same issue will be there.

Nobody complained there so I don't think it has the same problem, this seem to be a very specific bug around how dependencies and features are resolved.

**Comment by jpalus** [comment]
Can confirm `aardvark-dns 1.8.0` builds fine.

**Comment by lsm5** [comment]
guess we can close this?

**Comment by Luap99** [comment]
yes, although we should create CI tests for this mechanism to prevent releasing non working assets.
