### ISSUE TITLE
`README` needs an update for nftables

### ISSUE THREAD

**Issue by jpalus** [containers/netavark#900]
With initial nftables support in 1.10.0 I think README deserves an update since it still mentions future release:
https://github.com/containers/netavark/blob/992b2c150a7047affba165b73566ffad5d40df7b/README.md?plain=1#L13

**Comment by Luap99** [comment]
Do you want to open a PR for that?

**Comment by jpalus** [comment]
Didn't really plan a PR but felt obligation after the question :) #901 opened.
